name: 'Build'

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-18.04
    name: My first job
    steps:
    - name: first_step
      run:
        echo "first step"

    - name: second_step
      run:
        echo "second step"
