name: 'Linux Build'

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux-pipe:
    runs-on: ubuntu-20.04
    name: Linux pipeline
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: NodeJS initialization
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Packages installation
      run:
        npm install

    - name: Linting code
      run:
        npm run lint
   
    - name: Linting styles
      run:
        npm run lint:styls

    - name: Angular build
      run:
        npm run ng:build

    - name: Electron build and release
      run:
        npm run electron:build

